version: "3.9"

services:
  api1:
    build: ./api1
    environment:
      - DATABASE_URL=postgresql://user1:pass1@db1:5432/db1
      - BROKER_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - db1
      - rabbitmq
    ports:
      - "8001:8000"

  db1:
    image: postgres:15
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    volumes:
      - db1data:/var/lib/postgresql/data

  api2:
    build: ./api2
    environment:
      - DATABASE_URL=postgresql://user2:pass2@db2:5432/db2
      - BROKER_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - db2
      - rabbitmq
    ports:
      - "8002:8000"

  db2:
    image: postgres:15
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    volumes:
      - db2data:/var/lib/postgresql/data

  api3:
    build: ./api3
    environment:
      - DATABASE_URL=postgresql://user3:pass3@db3:5432/db3
      - BROKER_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - db3
      - rabbitmq
    ports:
      - "8003:8000"

  db3:
    image: postgres:15
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: pass3
      POSTGRES_DB: db3
    ports:
      - "5435:5432"
    volumes:
      - db3data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db1
      - db2
      - db3

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db1data:
  db2data:
  db3data: